// Generated by Wrangler on Mon Sep 16 2024 15:36:02 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	SKIP_DEPENDENCY_INSTALL: string;
	UNSTABLE_PRE_BUILD: string;
	NODE_V: string;
}
